name: Build 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - "src/**"
      - "pyproject.toml"

jobs:
  wheels:
    name: Build wheels on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runner: ubuntu-latest
            arch: x86_64

          - os: ubuntu-latest
            runner: ubuntu-24.04-arm
            arch: aarch64

          - os: macos-latest
            runner: macos-latest
            arch: universal2

          - os: windows-latest
            runner: windows-latest
            arch: AMD64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          # Python versions
          CIBW_BUILD: "cp310-* cp310-* cp311-* cp312-* cp313-* cp314-*"

          # Architectures
          CIBW_ARCHS: "${{ matrix.arch }}"

          CIBW_SKIP: "*-musllinux_*"
          CIBW_TEST_SKIP: "*"

          CIBW_BUILD_VERBOSITY: 1

